blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.CreatePostView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.UpdatePostView.as_view(), name='post_edit'),
    path('post/<int:pk>/remove', views.DeletePostView.as_view(), name='post_remove'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/comment', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove', views.comment_remove, name='comment_remove'),
    path('post/<int:pk>/publish', views.post_publish, name='post_publish'),

]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout', views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    title = models.CharField(max_length=256)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=256)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_list')

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from blog.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('author', 'title', 'text')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'})
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text')

        widgets = {
            'author': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from blog.forms import PostForm, CommentForm
from django.urls import reverse_lazy
from blog.models import Post, Comment
from django.views.generic import (TemplateView, ListView, DetailView,
                                  CreateView, UpdateView, DeleteView)

# Create your views here.


class AboutView(TemplateView):
    template_name = 'blog/about.html'


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-create_date')


class PostDetailView(DetailView):
    model = Post


class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post


class UpdatePostView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post


class DeletePostView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')


class DraftListView(LoginRequiredMixin, ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('create_date')


#######################################################################################################################

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=post.pk)


@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form': form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    comment.delete()
    return redirect('blog:post_detail', pk=post.pk)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="jumbotron">
    <h1>About Me!</h1>
    <h6>Thanks for Checking it Out!</h6>
    </div>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One&display=swap" rel="stylesheet">
</head>
<body class='loader'>
<nav class="navbar navbar-expand-lg bg-light techfont">
    <a class="navbar-brand" href="{% url 'blog:post_list' %}">My Tech blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:about'%}">About</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Social Network
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="https://www.facebook.com/ilham.mir68">Facebook</a>
                    <a class="dropdown-item" href="https://www.linkedin.com/in/ilham-mirzayev/">LinkedIn</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="https://gitlab.com/imirzayev">GitLab</a>
                </div>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:post_new' %}" >New Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:post_list' %}">Blogs</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:post_draft_list' %}">Drafts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}" >Log out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class='nav-link' href="{% url 'login' %}" ><span class="glyphicon glyphicon-user"></span>Login</a>
                </li>
                </ul>
            {% endif %}
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-0" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

{# The actual blog posts#}
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            <div class="blog_posts">
                <h1>Welcome: {{ user.username }}</h1>
                <br>
                <br>
                {% block content %}
                {% endblock %}

            </div>

        </div>
    </div>
</div>

{# SCRIPTS#}

<script type="text/javascript" src="{% static 'js/blog.js' %}"></script>

</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}

{% block content %}

    <h1>New Comment</h1>
    <form class="post-form" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-success">Post Comment</button>
    </form>

    <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure to delete {{ object }}?</p>
        <input type="submit" class="btn btn-danger" value="Confirm">
    </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1 class="posttitle loader">{{ post.title }}</h1>
    {% if post.published_date %}
        <div class="postdate">
            {{ post.published_date }}
        </div>
    {% else %}
        <a class="btn btn-danger" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
    {% endif %}

    <p class="postcontent">{{ post.title|safe|linebreaksbr }}</p>

    {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}">
            <span class="glyphicon glyphicon-pencil"></span>
        Edit
        </a>

        <a class="btn btn-primary" href="{% url 'blog:post_remove' pk=post.pk %}">
            <span class="glyphicon glyphicon-remove"></span>
        Delete
        </a>
    {% endif %}

    <hr>
    <a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment</a>

    <div class="container">
        {% for comment in post.comments.all %}
            <br>
            {% if user.is_authenticated or comment.approved_comment %}
                {{ comment.created_date }}
                {% if not comment.approved_comment %}
                    <a class="btn btn-primary" href="{% url 'blog:comment_remove' pk=comment.pk %}">
                        <span class="glyphicon glyphicon-remove"></span>
                    Delete
                    </a>

                    <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}">
                        <span class="glyphicon glyphicon-ok"></span>
                    Approve
                    </a>
                {% endif %}
                <p>{{ comment.text|safe|linebreaksbr }}</p>
                <p>Posted by: {{ comment.author }}</p>
            {% endif %}
        {% empty %}
            <p>No Comments!</p>
        {% endfor %}
    </div>

{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts%}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block content %}

    <h1>New Post</h1>
    <form class="post-form" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-success">Save</button>
    </form>

    <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="centerstage" xmlns="http://www.w3.org/1999/html">
        {% for post in post_list %}
            <div class="post">
                <h1><a href="{% url 'blog:post_detail' pk=post.pk %}"></a>{{ post.title }}</h1>
                <div class="date">
                    <p>Published on: {{ post.published_date|date:"D M Y" }}</p>
                </div>
                <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}